apiVersion: apps/v1
kind: Deployment
metadata:
  name: revhire-user
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revhire-user
  template:
    metadata:
      labels:
        app : revhire-user
    spec:
      containers:
        - name: revhire-user
          image: myregistryp2.azurecr.io/userservice:5
          
